# Docs: https://docs.gitlab.com/ce/pages/
image: jekyll/jekyll:latest

variables:
  JEKYLL_ENV: production

before_script:
- bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - gh-pages

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - gh-pages